// Typescript 2.0
export type INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_COUNTER : INCREMENT_COUNTER = 'INCREMENT_COUNTER';

export type DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';
export const DECREMENT_COUNTER : DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export type LOGOUT_USER = 'App/LOGOUT_USER';
export const LOGOUT_USER : LOGOUT_USER = 'App/LOGOUT_USER';
