export const PRIMARY_ATTACK_STAT_SET: "PRIMARY_ATTACK_STAT_SET" = "PRIMARY_ATTACK_STAT_SET";
export const PRIMARY_SPELL_STAT_SET: "PRIMARY_SPELL_STAT_SET" = "PRIMARY_SPELL_STAT_SET";

export const MISC_ATTACK_BONUS_SET: "MISC_ATTACK_BONUS_SET" = "MISC_ATTACK_BONUS_SET";
export const MISC_SAVE_DC_BONUS_SET: "MISC_SAVE_DC_BONUS_SET" = "MISC_SAVE_DC_BONUS_SET";
