export const TRAIT_APPLY: "TRAIT_APPLY" = "TRAIT_APPLY";
export const TRAIT_REMOVE: "TRAIT_REMOVE" = "TRAIT_REMOVE";

export const TRAIT_SET_APPLY: "TRAIT_SET_APPLY" = "TRAIT_SET_APPLY";
export const TRAIT_SET_REMOVE: "TRAIT_SET_REMOVE" = "TRAIT_SET_REMOVE";
