export const ACTION_APPLY: "ACTION_APPLY" = "ACTION_APPLY";
export const ACTION_REMOVE: "ACTION_REMOVE" = "ACTION_REMOVE";

// export const ACTION_ARGS_SET: "ACTION_ARGS_SET" = "ACTION_ARGS_SET";
export const ACTION_ARG_SET: "ACTION_ARG_SET" = "ACTION_ARG_SET";
export const ACTION_ARG_TYPE_SET: "ACTION_ARG_TYPE_SET" = "ACTION_ARG_TYPE_SET";
