
export const HIT_DICE_COUNT_SET: "HIT_DICE_COUNT_SET" = "HIT_DICE_COUNT_SET";
export const HIT_DIE_SIZE_SET: "HIT_DIE_SIZE_SET" = "HIT_DIE_SIZE_SET";

export const HIT_DIE_ADD_NEW: "HIT_DIE_ADD_NEW" = "HIT_DIE_ADD_NEW";
export const HIT_DIE_REMOVE: "HIT_DIE_REMOVE" = "HIT_DIE_REMOVE";

export const SIZE_SET: "SIZE_SET" = "SIZE_SET";
export const SIZE_OVERRIDE_TOGGLE: "SIZE_OVERRIDE_TOGGLE" = "SIZE_OVERRIDE_TOGGLE";

export const TEMP_AC_SET: "TEMP_AC_SET" = "TEMP_AC_SET";
