
export const SET_HIT_DICE_COUNT: "SET_HIT_DICE_COUNT" = "SET_HIT_DICE_COUNT";
export const SET_HIT_DIE_SIZE: "SET_HIT_DIE_SIZE" = "SET_HIT_DIE_SIZE";

export const ADD_NEW_HIT_DIE: "ADD_NEW_HIT_DIE" = "ADD_NEW_HIT_DIE";
export const REMOVE_HIT_DIE: "REMOVE_HIT_DIE" = "REMOVE_HIT_DIE";
