export const SAVE_PROFICIENCY_ADD: "SAVE_PROFICIENCY_ADD" = "SAVE_PROFICIENCY_ADD";
export const SAVE_PROFICIENCY_REMOVE: "SAVE_PROFICIENCY_REMOVE" = "SAVE_PROFICIENCY_REMOVE";

export const SAVE_EXPERTISE_ADD: "SAVE_EXPERTISE_ADD" = "SAVE_EXPERTISE_ADD";
export const SAVE_EXPERTISE_REMOVE: "SAVE_EXPERTISE_REMOVE" = "SAVE_EXPERTISE_REMOVE";

export const SAVE_BONUS_MODIFY: "SAVE_BONUS_MODIFY" = "SAVE_BONUS_MODIFY";
