export const ADD_SAVE_PROFICIENCY: "ADD_SAVE_PROFICIENCY" = "ADD_SAVE_PROFICIENCY";
export const REMOVE_SAVE_PROFICIENCY: "REMOVE_SAVE_PROFICIENCY" = "REMOVE_SAVE_PROFICIENCY";

export const MODIFY_SAVE_BONUS: "MODIFY_SAVE_BONUS" = "MODIFY_SAVE_BONUS";
