export const APPLY_TRAIT: "APPLY_TRAIT" = "APPLY_TRAIT";
export const REMOVE_TRAIT: "REMOVE_TRAIT" = "REMOVE_TRAIT";

export const APPLY_TRAIT_TEMPLATE: "APPLY_TRAIT_TEMPLATE" = "APPLY_TRAIT_TEMPLATE";
export const REMOVE_TRAIT_TEMPLATE: "REMOVE_TRAIT_TEMPLATE" = "REMOVE_TRAIT_TEMPLATE";
