export const TRAIT_APPLY: "TRAIT_APPLY" = "TRAIT_APPLY";
export const TRAIT_REMOVE: "TRAIT_REMOVE" = "TRAIT_REMOVE";

export const TRAIT_TEMPLATE_APPLY: "TRAIT_TEMPLATE_APPLY" = "TRAIT_TEMPLATE_APPLY";
export const TRAIT_TEMPLATE_REMOVE: "TRAIT_TEMPLATE_REMOVE" = "TRAIT_TEMPLATE_REMOVE";
